=== alliedtelesis/apteryx-xml/apteryx.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="https://github.com/alliedtelesis/apteryx"
	xmlns="https://github.com/alliedtelesis/apteryx"
	elementFormDefault="qualified">
	<xs:element name="VALUE">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="value" type="xs:string" use="required" />
			<xs:attribute name="help" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="PROVIDE">
	</xs:element>
	<xs:element name="INDEX">
	</xs:element>
	<xs:element name="WATCH">
	</xs:element>
	<xs:element name="NODE">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="NODE" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="VALUE" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="WATCH" minOccurs="0" maxOccurs="1" />
				<xs:element ref="PROVIDE" minOccurs="0" maxOccurs="1" />
				<xs:element ref="INDEX" minOccurs="0" maxOccurs="1" />
				<xs:element ref="REFRESH" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="default" type="xs:string" use="optional" />
			<xs:attribute name="pattern" type="xs:string" use="optional" />
			<xs:attribute name="help" type="xs:string" use="optional" />
			<xs:attribute name="mode" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="(p|x|hx|[rhwc]{1,4})"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="SCRIPT">
	</xs:element>
	<xs:element name="MODULE">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SCRIPT" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="NODE" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== alliedtelesis/apteryx-xml/models/xlat_test.xml
<?xml version='1.0' encoding='UTF-8'?>
<MODULE xmlns="http://test.com/ns/yang/xlat-testing"
    xmlns:xlat-test="http://test.com/ns/yang/xlat-testing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://github.com/alliedtelesis/apteryx-xml https://github.com/alliedtelesis/apteryx-xml/releases/download/v1.2/apteryx.xsd"
    model="xlat-test" organization="Test Ltd" version="2023-01-01">
    <NODE name="xlat-test" help="This is a test node">
        <NODE name="xlat-animals">
            <NODE name="xlat-animal" help="This is a list of animals">
                <NODE name="*" help="The animal entry with key name">
                    <NODE name="name" mode="rw" help="This is the name of the animal" />
                    <NODE name="type" mode="rw" default="big" help="This is the type of the animal">
                        <VALUE name="fast" value="3" />
                        <VALUE name="slow" value="4" />
                    </NODE>
                    <NODE name="colour" mode="rw" help="This is the colour of the animal" />
                    <NODE name="food">
                        <NODE name="*" help="This is a list of food">
                            <NODE name="name" mode="rw" help="Food name" />
                            <NODE name="type" mode="rw" help="Food type" />
                        </NODE>
                    </NODE>
                    <NODE name="toys">
                        <NODE name="toy" help="This is a leaf list of toys">
                            <NODE name="*" mode="rw" help="List of toys" />
                        </NODE>
                    </NODE>
                </NODE>
            </NODE>
        </NODE>
    </NODE>
</MODULE>

=== alliedtelesis/apteryx-xml/models/test.xml
<?xml version='1.0' encoding='UTF-8'?>
<MODULE xmlns="http://test.com/ns/yang/testing"
        xmlns:test="http://test.com/ns/yang/testing"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://github.com/alliedtelesis/apteryx-xml https://github.com/alliedtelesis/apteryx-xml/releases/download/v1.2/apteryx.xsd"
        model="testing" organization="Test Ltd" version="2023-01-01" features="test-time,dummy">
  <NODE name="test" help="This is a test node">
    <NODE name="settings" help="Settings">
      <NODE name="description" mode="rw" help="string"/>
      <NODE name="debug" mode="rw" default="disable" help="Debug configuration">
        <VALUE name="disable" value="0" help="Debugging is disabled"/>
        <VALUE name="enable" value="1" help="Debugging is enabled"/>
      </NODE>
      <NODE name="enable" mode="rw" default="false" help="boolean">
        <VALUE name="true" value="true"/>
        <VALUE name="false" value="false"/>
      </NODE>
      <NODE name="empty" help="an empty container">
      </NODE>
      <NODE name="priority" mode="rw" help="integer" range="-5..-1 | 1..5 | 99"/>
      <NODE name="writeonly" mode="w" help="A write only field"/>
      <NODE name="readonly" mode="r" default="yes" help="A read only field">
        <VALUE name="yes" value="0" help="This is read only"/>
        <VALUE name="no" value="1" help="This is not read only"/>
      </NODE>
      <NODE name="hidden" mode="h" help="A hidden field"/>
      <NODE name="time" help="time">
        <NODE name="day" mode="rw" help="day" range="1..31"/>
        <NODE name="hour" mode="rw" help="hour" range="0..23"/>
        <NODE name="minute" mode="rw" help="minute" range="0..59"/>
        <NODE name="second" mode="rw" help="second" range="0..59"/>
        <NODE name="active" mode="r" default="false" help="boolean">
          <VALUE name="true" value="true"/>
          <VALUE name="false" value="false"/>
        </NODE>
      </NODE>
      <NODE name="magictime" if-feature="magic" help="magic time">
        <NODE name="days" mode="rw" help="days" range="1..31"/>
        <NODE name="hours" mode="rw" help="hours" range="0..23"/>
        <NODE name="minutes" mode="rw" help="minutes" range="0..59"/>
        <NODE name="seconds" mode="rw" help="seconds" range="0..59"/>
      </NODE>
      <NODE name="testtime" if-feature="test-time" help="test time">
        <NODE name="days" mode="rw" help="days" range="1..31"/>
        <NODE name="hours" if-feature="bogus or dummy" mode="rw" help="hours" range="0..23"/>
        <NODE name="minutes" if-feature="bogus or dummy or mins" mode="rw" help="minutes" range="0..59"/>
        <NODE name="seconds" if-feature="bogus or bogon or mins" mode="rw" help="seconds" range="0..59"/>
      </NODE>
      <NODE name="complextime" help="complex time">
        <NODE name="days" when="../../../settings" mode="rw" help="days" range="1..31"/>
        <NODE name="hours" when="name(../..) = 'settings'" mode="rw" help="hours" range="0..23"/>
        <NODE name="minutes" when="name(../..) != 'settings'" mode="rw" help="minutes" range="0..59"/>
        <NODE name="seconds" when="count(../../..) = '3'" mode="rw" help="seconds" range="0..59"/>
      </NODE>
      <NODE name="users" help="This is a list of users">
        <NODE name="*" help="The user entry with key name">
          <NODE name="name" mode="rw" help="This is the name of the user"/>
          <NODE name="age" mode="rw" help="integer" range="0|1..99"/>
          <NODE name="active" mode="r" default="false" help="boolean">
            <VALUE name="true" value="true"/>
            <VALUE name="false" value="false"/>
          </NODE>
          <NODE name="groups" help="This is a leaf list of integers">
            <NODE name="*" mode="rw" help="Member of group" range="1..999"/>
          </NODE>
        </NODE>
      </NODE>
      <NODE name="rules" help="This is a list of rules with numerical indexes">
        <NODE name="*" help="The rule entry with key index">
          <NODE name="index" mode="rw" help="integer" range="1..999"/>
          <NODE name="name" mode="rw" help="This is the name of the rule"/>
        </NODE>
      </NODE>
    </NODE>
    <NODE name="state" help="State">
      <NODE name="counter" mode="r" default="0" help="uint32" range="0..4294967295"/>
      <NODE name="uptime" help="uptime">
        <NODE name="days" mode="r" help="days" range="1..31"/>
        <NODE name="hours" mode="r" help="hours" range="0..23"/>
        <NODE name="minutes" mode="r" help="minutes" range="0..59"/>
        <NODE name="seconds" mode="r" help="seconds" range="0..59"/>
      </NODE>
      <NODE name="downtime" help="downtime">
        <NODE name="days" mode="r" help="days" range="1..31"/>
        <NODE name="hours" mode="r" help="hours" range="0..23"/>
        <NODE name="minutes" mode="r" help="minutes" range="0..59"/>
        <NODE name="seconds" mode="r" help="seconds" range="0..59"/>
      </NODE>
      <NODE name="romembers" help="A read-only leaf-list">
        <NODE name="*" mode="r" help="Member of group"/>
      </NODE>
    </NODE>
    <NODE name="animals">
      <NODE name="animal" help="This is a list of animals">
        <NODE name="*" key="name" help="The animal entry with key name">
          <NODE name="name" mode="rw" help="This is the name of the animal"/>
          <NODE name="type" idref_href="http://test.com/ns/yang/animal-types" idref_prefix="a-types" idref_module="animal-testing-types" mode="rw" default="big" help="This is the type of the animal">
            <VALUE name="big" value="1"/>
            <VALUE name="little" value="2"/>
          </NODE>
          <NODE name="colour" mode="rw" help="This is the colour of the animal"/>
          <NODE name="food">
              <NODE name="*" help="This is a list of food">
                  <NODE name="name" mode="rw" help="Food name"/>
                  <NODE name="type" mode="rw" help="Food type"/>
              </NODE>
              <REFRESH>Sample REFRESH node</REFRESH>
          </NODE>
          <NODE name="config" >
            <NODE name="type" mode="rw" default="big">
              <VALUE name="big" value="1"/>
              <VALUE name="little" value="2"/>
            </NODE>
          </NODE>
          <NODE name="toys" when="test:config/test:type != '1'" >
            <NODE name="toy" help="This is a leaf list of toys">
              <NODE name="*" mode="rw" help="List of toys"/>
              <WATCH>Sample WATCH node</WATCH>
            </NODE>
          </NODE>
          <NODE name="houses" when="../name = 'dog'">
            <NODE name="house" help="This is a leaf list of pet houses">
              <NODE name="*" mode="rw" help="List of houses"/>
            </NODE>
          </NODE>
          <NODE name="cages" when="../type = 'big'">
            <NODE name="cage" help="This is a leaf list of pet houses">
              <NODE name="*" mode="rw" help="List of houses"/>
            </NODE>
          </NODE>
          <NODE name="claws" when="../../wombat" mode="rw" help="claws per paw"/>
          <NODE name="friend" must="../../cat" mode="rw" help="animal friend"/>
          <NODE name="n-type" when="derived-from-or-self(./type, 'a-types:type')" mode="rw" help="animal n-type"/>
        </NODE>
      </NODE>
    </NODE>
    <NODE name="patterns">
      <NODE name="variable_1" mode="rw" help="variable to test /(flash|card|usb):/?[\.A-Za-z0-9_\-]{1,251}\.cfg/" pattern="(flash|card|usb):/?[\.A-Za-z0-9_\-]{1,251}\.cfg"/>
    </NODE>
    <NODE name="objects" help="A generic object">
      <NODE name="object" mode="rw" help="One object in a list">
        <NODE name="*" help="The object's key - the name variable below">
          <NODE name="name" mode="rw" help="This is the name of the object"/>
          <NODE name="top-container" mode="rw" help="The top container in the object">
            <NODE name="conf" mode="rw" help="The config for the top container">
              <NODE name="enabled" mode="rw" help="Whether the top container is enabled" default="true">
                <VALUE name="true" value="1"/>
                <VALUE name="false" value="2"/>
              </NODE>
            </NODE>
            <NODE name="inner-container" mode="rw" help="The inner container in the object">
              <NODE name="conf" mode="rw" help="The config for the top container">
                <NODE name="enabled" mode="rw" help="Whether the top container is enabled" default="false">
                  <VALUE name="true" value="1"/>
                  <VALUE name="false" value="2"/>
                </NODE>
              </NODE>
            </NODE>
          </NODE>
        </NODE>
      </NODE>
    </NODE>
    <NODE name="friends" help="This is a list with 2 keys">
      <NODE name="*" mode="rw" key="name age" help="The friends entry with key name age">
        <NODE name="name" mode="rw" help="name"/>
        <NODE name="age" mode="rw" range="0..100" help="age"/>
        <NODE name="gender" mode="rw" default="male" help="gender">
          <VALUE name="male" value="male"/>
          <VALUE name="female" value="female"/>
        </NODE>
        <NODE name="alive" mode="rw" default="true" help="alive">
          <VALUE name="true" value="true"/>
          <VALUE name="false" value="false"/>
        </NODE>
      </NODE>
    </NODE>
  </NODE>
  <NODE name="test-list" help="This is top-level list">
    <NODE name="*" help="The list entry with key index">
      <NODE name="index" mode="rw" help="integer" range="1..999"/>
      <NODE name="name" mode="rw" help="This is the name of the list entry"/>
    </NODE>
  </NODE>
  <NODE name="test-leaflist" help="This is top-level leaf-list">
    <NODE name="*" mode="rw" help="The list entry"/>
  </NODE>
</MODULE>

=== alliedtelesis/apteryx-xml/models/test4:rpc.xml
<?xml version='1.0' encoding='UTF-8'?>
<MODULE xmlns="http://test.com/ns/yang/testing-4"
        xmlns:test="http://test.com/ns/yang/testing"
        xmlns:t4="http://test.com/ns/yang/testing-4"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://github.com/alliedtelesis/apteryx-xml https://github.com/alliedtelesis/apteryx-xml/releases/download/v1.2/apteryx.xsd"
        model="testing-4" organization="Test 4 Ltd" version="2024-02-01">
  <NODE name="test" help="This is a test node in the testing-4 namespace">
    <NODE name="state" help="State">
      <NODE name="age" mode="r" help="a string"/>
      <NODE name="history" help="List of last reset times">
        <NODE name="*" help="Reset time" range="0..4294967295"/>
      </NODE>
      <NODE name="reset" mode="rwx" help="Reset state">
        <NODE name="input" help="Input parameters">
          <NODE name="delay" mode="w" help="Number of seconds to wait before starting the reset" range="0..4294967295"/>
        </NODE>
        <NODE name="output" help="Output parameters">
          <NODE name="delay" mode="r" help="Last number of seconds waited before reset" range="0..4294967295"/>
        </NODE>
      </NODE>
      <NODE name="get-last-reset-time" mode="rwx" help="Retrieve the last interface reset time">
        <NODE name="output" help="Output parameters">
          <NODE name="last-reset" mode="r" help="Time of the last reset" range="0..4294967295"/>
          <NODE name="history" help="List of last reset times">
            <NODE name="*" help="Last reset time" range="0..4294967295"/>
          </NODE>
        </NODE>
      </NODE>
      <NODE name="get-reset-history" mode="rwx" help="Retrieve the history of resets">
        <NODE name="output" help="Output parameters">
          <NODE name="last-reset" mode="r" help="Time of the last reset" range="0..4294967295"/>
          <NODE name="history" help="List of last reset times">
            <NODE name="*" help="Last reset time" range="0..4294967295"/>
          </NODE>
        </NODE>
      </NODE>
      <NODE name="users" help="This is a list of users">
        <NODE name="*" help="The user entry with key name">
          <NODE name="name" mode="rw" help="This is the name of the user"/>
          <NODE name="age" mode="rw" help="Age of the user" range="0..4294967295"/>
          <NODE name="_" mode="rwx" help="get/add/delete users">
            <NODE name="input" help="Input parameters">
              <NODE name="name" mode="w" help="User name"/>
              <NODE name="age" mode="w" help="User age" range="0..4294967295"/>
            </NODE>
            <NODE name="output" help="Input parameters">
              <NODE name="users" help="This is a list of users">
                <NODE name="*" help="The user entry with key name">
                  <NODE name="name" mode="r" help="User name"/>
                  <NODE name="age" mode="r" help="User age" range="0..4294967295"/>
                </NODE>
              </NODE>
            </NODE>
          </NODE>
          <NODE name="set-age" mode="rwx" help="Set the users age">
            <NODE name="input" help="Input parameters">
              <NODE name="age" mode="w" help="New age" range="0..4294967295"/>
            </NODE>
          </NODE>
        </NODE>
      </NODE>
    </NODE>
  </NODE>
  <test:NODE name="operations" help="Container for all operation resources.">
    <NODE name="reboot" mode="rwx" help="Reboot operation.">
      <NODE name="input" help="Input parameters">
        <NODE name="delay" mode="w" help="Number of seconds to wait before initiating the reboot operation." range="0..4294967295"/>
        <NODE name="message" mode="w" help="Log message to display when reboot is started."/>
        <NODE name="language" mode="w" help="Language identifier string."/>
      </NODE>
    </NODE>
    <NODE name="get-reboot-info" mode="rwx" help="Retrieve parameters used in the last reboot operation.">
      <NODE name="output" help="Output parameters">
        <NODE name="reboot-time" mode="r" help="The 'delay' parameter used in the last reboot operation." range="0..4294967295"/>
        <NODE name="message" mode="r" help="The 'message' parameter used in the last reboot operation."/>
        <NODE name="language" mode="r" help="The 'language' parameter used in the last reboot operation."/>
      </NODE>
    </NODE>
    <NODE name="get-rpcs" mode="rwx" help="Retrieve the list of all RPCs">
      <NODE name="output" help="Output parameters">
        <NODE name="paths" help="List of RPCs">
          <NODE name="*" help="An RPC">
            <NODE name="path" mode="r" help="RPC path"/>
            <NODE name="methods" help="List of methods this RPC supports">
              <NODE name="*" mode="r" help="A method" pattern="POST|GET|PUT|PATCH|DELETE|HEAD|OPTIONS"/>
            </NODE>
          </NODE>
        </NODE>
      </NODE>
    </NODE>
  </test:NODE>
</MODULE>

=== alliedtelesis/apteryx-xml/models/test2:test2.xml
<?xml version='1.0' encoding='UTF-8'?>
<MODULE xmlns="http://test.com/ns/yang/testing-2" 
        xmlns:t2="http://test.com/ns/yang/testing-2"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://github.com/alliedtelesis/apteryx-xml https://github.com/alliedtelesis/apteryx-xml/releases/download/v1.2/apteryx.xsd"
        model="testing-2" organization="Test 2 Ltd" version="2023-02-01">
  <NODE name="test" help="This is a test node">
    <NODE name="settings" help="Settings">
      <NODE name="priority" mode="rw" help="integer" range="1..5"/>
      <NODE name="users" help="This is a list of users">
        <NODE name="*" help="The user entry with key name">
          <NODE name="name" mode="rw" help="This is the name of the user"/>
        </NODE>
      </NODE>
    </NODE>
    <NODE name="state" help="State">
      <NODE name="priority" mode="r" help="integer"/>
    </NODE>
  </NODE>
</MODULE>
